apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-003
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/pv003
    server: 192.168.80.63