apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-002
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi