apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-002
  namespace: kube-system
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/pv002
    server: 192.168.80.63