apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-005
spec:
  containers:
  - name: container-nfs-005
    image: harbor.io/k8s/nginx:1.11
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: nfs-volume-nginx-data
      mountPath: "/nginx/html"
    ports:
    - containerPort:80
  restartPolicy: "Never"
  volumes:
  - name: nfs-volume-nginx-data
    PersistentVolumeClaim:
      claimName: nfs-pvc-005

