apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-001
  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs/pv001
    server: 192.168.80.63